name: Lint and Test

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pylint
        run: pylint src/

      - name: Run flake8
        run: flake8 src/

      - name: Run bandit
        run: bandit -r src/

      - name: Run tests
        run: pytest tests/
